server:
  port: 8080

spring:
  application:
    name: elecciones-backend

  datasource:
    url: jdbc:postgresql://127.0.0.1:5433/elecciones2026
    username: elecciones
    password: elecciones

  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

app:
  jwt:
    secret: "elecciones-colombia-2026-secret-key-super-segura-32chars"
    expiration-minutes: 480

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics