CREATE TABLE app_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ(6),
    updated_at TIMESTAMPTZ(6),
    active BOOLEAN NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(255),
    CONSTRAINT app_user_role_check CHECK (role IN ('ADMINISTRADOR', 'ANALISTA'))
);

CREATE TABLE audit_event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    action VARCHAR(255),
    at TIMESTAMPTZ(6),
    details VARCHAR(1500),
    entity VARCHAR(255),
    entity_id BIGINT,
    ip VARCHAR(255),
    success BOOLEAN NOT NULL,
    username VARCHAR(255)
);

CREATE TABLE election (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ(6),
    updated_at TIMESTAMPTZ(6),
    election_date DATE,
    name VARCHAR(255),
    round VARCHAR(255),
    state VARCHAR(255),
    type VARCHAR(255),
    CONSTRAINT election_round_check CHECK (round IN ('NINGUNA', 'PRIMERA', 'SEGUNDA')),
    CONSTRAINT election_state_check CHECK (state IN ('CONFIGURADA', 'ABIERTA', 'EN_CONTEO', 'CERRADA', 'ARCHIVADA')),
    CONSTRAINT election_type_check CHECK (type IN ('SENADO', 'CAMARA', 'PRESIDENCIA'))
);

CREATE TABLE party (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ(6),
    updated_at TIMESTAMPTZ(6),
    acronym VARCHAR(255) NOT NULL UNIQUE,
    active BOOLEAN NOT NULL,
    color VARCHAR(255),
    foundation_year INTEGER,
    name VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE poll (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ(6),
    updated_at TIMESTAMPTZ(6),
    date DATE,
    margin_error DOUBLE PRECISION,
    methodology VARCHAR(255),
    sample_size INTEGER,
    source VARCHAR(255)
);

CREATE TABLE candidate (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ(6),
    updated_at TIMESTAMPTZ(6),
    active BOOLEAN NOT NULL,
    department VARCHAR(255),
    election_type VARCHAR(255),
    municipality VARCHAR(255),
    name VARCHAR(255) NOT NULL,
    vice_president_name VARCHAR(255),
    party_id BIGINT NOT NULL,
    CONSTRAINT candidate_election_type_check CHECK (election_type IN ('SENADO', 'CAMARA', 'PRESIDENCIA')),
    CONSTRAINT candidate_party_fk FOREIGN KEY (party_id) REFERENCES party(id)
);

CREATE TABLE official_result (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ(6),
    updated_at TIMESTAMPTZ(6),
    department VARCHAR(255),
    imported_at TIMESTAMPTZ(6),
    municipality VARCHAR(255),
    participation DOUBLE PRECISION,
    percentage DOUBLE PRECISION,
    reported_tables INTEGER,
    source VARCHAR(255),
    total_tables INTEGER,
    votes BIGINT,
    candidate_id BIGINT NOT NULL,
    election_id BIGINT NOT NULL,
    CONSTRAINT official_result_election_fk FOREIGN KEY (election_id) REFERENCES election(id),
    CONSTRAINT official_result_candidate_fk FOREIGN KEY (candidate_id) REFERENCES candidate(id)
);

CREATE TABLE poll_result (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ(6),
    updated_at TIMESTAMPTZ(6),
    percentage DOUBLE PRECISION,
    candidate_id BIGINT NOT NULL,
    poll_id BIGINT NOT NULL,
    CONSTRAINT poll_result_candidate_fk FOREIGN KEY (candidate_id) REFERENCES candidate(id),
    CONSTRAINT poll_result_poll_fk FOREIGN KEY (poll_id) REFERENCES poll(id)
);

CREATE INDEX idx_candidate_party_id ON candidate(party_id);
CREATE INDEX idx_official_result_election_id ON official_result(election_id);
CREATE INDEX idx_official_result_candidate_id ON official_result(candidate_id);
CREATE INDEX idx_poll_result_poll_id ON poll_result(poll_id);
CREATE INDEX idx_poll_result_candidate_id ON poll_result(candidate_id);
CREATE INDEX idx_audit_event_at ON audit_event(at DESC);
CREATE INDEX idx_poll_date ON poll(date DESC);
