CREATE TABLE assistant_session (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    session_key UUID NOT NULL,
    election_id BIGINT,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    provider VARCHAR(30) NOT NULL DEFAULT 'GEMINI',
    model VARCHAR(100),
    last_activity_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    message_count INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT assistant_session_key_uk UNIQUE (session_key),
    CONSTRAINT assistant_session_election_fk
        FOREIGN KEY (election_id) REFERENCES election(id),
    CONSTRAINT assistant_session_status_ck
        CHECK (status IN ('ACTIVE', 'CLOSED')),
    CONSTRAINT assistant_session_message_count_ck
        CHECK (message_count >= 0)
);

CREATE TABLE assistant_message (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    session_id BIGINT NOT NULL,
    role VARCHAR(20) NOT NULL,
    content TEXT NOT NULL,
    provider VARCHAR(30),
    model VARCHAR(100),
    intent VARCHAR(80),
    tools_used VARCHAR(1000),
    fallback BOOLEAN NOT NULL DEFAULT FALSE,
    response_time_ms BIGINT,
    helpful BOOLEAN,
    feedback_comment VARCHAR(500),
    CONSTRAINT assistant_message_session_fk
        FOREIGN KEY (session_id) REFERENCES assistant_session(id),
    CONSTRAINT assistant_message_role_ck
        CHECK (role IN ('USER', 'ASSISTANT')),
    CONSTRAINT assistant_message_response_time_ck
        CHECK (response_time_ms IS NULL OR response_time_ms >= 0)
);

CREATE INDEX idx_assistant_session_election
    ON assistant_session (election_id);

CREATE INDEX idx_assistant_session_activity
    ON assistant_session (last_activity_at DESC);

CREATE INDEX idx_assistant_message_session_created
    ON assistant_message (session_id, created_at, id);

CREATE INDEX idx_assistant_message_provider
    ON assistant_message (provider, created_at DESC);
