-- V9: Integridad para usuarios, auditoría y generación de reportes.
-- No elimina datos de negocio. Puede detenerse si existen correos duplicados al normalizar.

DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM app_user
        GROUP BY lower(btrim(email))
        HAVING count(*) > 1
    ) THEN
        RAISE EXCEPTION 'V9 no puede continuar: existen correos de usuario duplicados ignorando mayúsculas o espacios';
    END IF;
END $$;

UPDATE app_user
SET email = lower(btrim(email)),
    name = btrim(name),
    created_at = COALESCE(created_at, CURRENT_TIMESTAMP),
    updated_at = COALESCE(updated_at, created_at, CURRENT_TIMESTAMP),
    role = COALESCE(role, 'ANALISTA')
WHERE email <> lower(btrim(email))
   OR name <> btrim(name)
   OR created_at IS NULL
   OR updated_at IS NULL
   OR role IS NULL;

ALTER TABLE app_user
    ADD COLUMN IF NOT EXISTS last_login_at TIMESTAMPTZ(6);

ALTER TABLE app_user
    ALTER COLUMN created_at SET DEFAULT CURRENT_TIMESTAMP,
    ALTER COLUMN created_at SET NOT NULL,
    ALTER COLUMN updated_at SET DEFAULT CURRENT_TIMESTAMP,
    ALTER COLUMN updated_at SET NOT NULL,
    ALTER COLUMN role SET NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS uq_app_user_email_normalized
    ON app_user (lower(btrim(email)));
CREATE INDEX IF NOT EXISTS idx_app_user_active_role
    ON app_user (active, role);
CREATE INDEX IF NOT EXISTS idx_app_user_last_login_at
    ON app_user (last_login_at DESC NULLS LAST);

UPDATE audit_event
SET at = COALESCE(at, CURRENT_TIMESTAMP),
    username = COALESCE(NULLIF(btrim(username), ''), 'sistema'),
    action = COALESCE(NULLIF(btrim(action), ''), 'SIN_ACCION'),
    entity = COALESCE(NULLIF(btrim(entity), ''), 'SISTEMA'),
    details = COALESCE(NULLIF(btrim(details), ''), 'Sin detalle')
WHERE at IS NULL
   OR username IS NULL OR btrim(username) = ''
   OR action IS NULL OR btrim(action) = ''
   OR entity IS NULL OR btrim(entity) = ''
   OR details IS NULL OR btrim(details) = '';

ALTER TABLE audit_event
    ALTER COLUMN at SET DEFAULT CURRENT_TIMESTAMP,
    ALTER COLUMN at SET NOT NULL,
    ALTER COLUMN username SET NOT NULL,
    ALTER COLUMN action SET NOT NULL,
    ALTER COLUMN entity SET NOT NULL,
    ALTER COLUMN details SET NOT NULL;

CREATE INDEX IF NOT EXISTS idx_audit_event_at_desc
    ON audit_event (at DESC, id DESC);
CREATE INDEX IF NOT EXISTS idx_audit_event_action_entity
    ON audit_event (action, entity);
CREATE INDEX IF NOT EXISTS idx_audit_event_success_at
    ON audit_event (success, at DESC);
CREATE INDEX IF NOT EXISTS idx_audit_event_username_at
    ON audit_event (lower(username), at DESC);

CREATE OR REPLACE FUNCTION prevent_audit_event_mutation()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    RAISE EXCEPTION 'Los registros de auditoría son inmutables';
END;
$$;

DROP TRIGGER IF EXISTS trg_audit_event_immutable ON audit_event;
CREATE TRIGGER trg_audit_event_immutable
BEFORE UPDATE OR DELETE ON audit_event
FOR EACH ROW
EXECUTE FUNCTION prevent_audit_event_mutation();

CREATE TABLE IF NOT EXISTS report_generation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    election_id BIGINT NOT NULL,
    format VARCHAR(10) NOT NULL,
    requested_by VARCHAR(255) NOT NULL,
    record_count BIGINT NOT NULL DEFAULT 0,
    generated_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT report_generation_election_fk
        FOREIGN KEY (election_id) REFERENCES election(id),
    CONSTRAINT report_generation_format_ck
        CHECK (format IN ('PDF', 'CSV', 'JSON')),
    CONSTRAINT report_generation_record_count_ck
        CHECK (record_count >= 0)
);

CREATE INDEX IF NOT EXISTS idx_report_generation_election_format_date
    ON report_generation (election_id, format, generated_at DESC, id DESC);
CREATE INDEX IF NOT EXISTS idx_report_generation_requested_by_date
    ON report_generation (lower(requested_by), generated_at DESC);
